
services:
  postgres:
    image: postgres:latest
    container_name: local_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: isadora
    volumes:
      - pg_data:/var/lib/mysql
    ports:
      - "5432:5432"
    restart: always
