version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: local_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: isadora
    ports:
      - "5432:5432"
    volumes:
      - D:\projetos\isadora\pg_data:/var/lib/postgresql/data
    restart: always
